#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — moving glasgowtheatre.com to Cloudflare Pages with a daily build.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

banner "glasgowtheatre.com → Cloudflare"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
say "Everything here is on Cloudflare's free tier: Pages, DNS and one Worker."
open_url "https://dash.cloudflare.com/sign-up"
step "Sign up, or log in if you already have an account."
step "Verify your email address if prompted — the next stage needs it done."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Add glasgowtheatre.com to Cloudflare"
say "Cloudflare scans your existing DNS first, so the site keeps working on"
say "GitHub Pages until we deliberately switch it over in stage 7."
open_url "https://dash.cloudflare.com/?to=/:account/add-site"
step "Enter: glasgowtheatre.com"
step "Choose the Free plan."
step "Let it scan and import the existing records. Check the four A records"
step "  (185.199.108-111.153) and the www CNAME came across, then continue."
step "Cloudflare will show two nameservers ending in .ns.cloudflare.com"
ask CF_NS1 "First Cloudflare nameserver:"
ask CF_NS2 "Second Cloudflare nameserver:"
write_env CF_NS1 "$CF_NS1"
write_env CF_NS2 "$CF_NS2"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Point Porkbun at Cloudflare"
warn "This changes who answers DNS for the live domain."
say "Records were copied in stage 2, so the site stays up. Propagation is"
say "usually minutes, occasionally a few hours. Porkbun stays your registrar."
confirm "Change the nameservers at Porkbun now?"
open_url "https://porkbun.com/account/domainsSpeedy"
step "Find glasgowtheatre.com and open its NAMESERVERS section."
step "Replace all four Porkbun nameservers with these two:"
say ""
say "    $CF_NS1"
say "    $CF_NS2"
say ""
step "Save, then come back here."
pause
say "Checking what the world sees now..."
dig +short NS glasgowtheatre.com | sed 's/^/    /' || true
say "(Still showing porkbun.com is normal — it can take a while to propagate.)"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Resend — email for the daily report"
say "The build emails you only when new shows appear."
open_url "https://resend.com/signup"
step "Sign up (the free tier covers 3,000 emails a month)."
step "Go to API Keys → Create API Key. Sending access is enough."
ask_secret RESEND_API_KEY "Paste the Resend API key (starts re_):"
step "Now the address the report should go to."
ask REPORT_TO "Email address for the daily report:"
write_env RESEND_API_KEY "$RESEND_API_KEY"
write_env REPORT_TO "$REPORT_TO"
say ""
say "Until you verify a sending domain, Resend only delivers to the address"
say "that owns the account, from onboarding@resend.dev. That is fine to start."
say "To send from glasgowtheatre.com later: Resend → Domains → Add domain,"
say "then paste the records into Cloudflare DNS and set REPORT_FROM."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the Pages project"
say "Cloudflare builds the site from GitHub on every push, and daily."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create/pages"
step "Choose 'Connect to Git' and authorise Cloudflare for your GitHub account."
step "Pick the repository: shstkvch/glasgowtheatre-com"
step "Production branch: main"
step "Set these exactly:"
say ""
say "    Build command:      npm run build:cloudflare"
say "    Build output dir:   dist"
say "    Root directory:     (leave blank)"
say ""
step "Do NOT deploy yet if it lets you skip — env vars come next. If it builds"
step "  now, that is fine too; it will just use the keyword tag fallback."
ask CF_PAGES_PROJECT "Project name Cloudflare gave it (e.g. glasgowtheatre-com):"
write_env CF_PAGES_PROJECT "$CF_PAGES_PROJECT"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Pages environment variables"
say "These make tagging and the report work in the build."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT/settings/environment-variables"
step "Under Production, add each of these as a plaintext variable:"
say ""
say "    OPENROUTER_API_KEY   $(_existing OPENROUTER_API_KEY >/dev/null 2>&1 && echo '(the value in your .env)' || echo '(your OpenRouter key)')"
say "    RESEND_API_KEY       (the value just saved to .env)"
say "    REPORT_TO            $REPORT_TO"
say ""
say "Your local .env holds the exact values if you need to copy them:"
say "    grep -E 'OPENROUTER_API_KEY|RESEND_API_KEY|REPORT_TO' .env"
say ""
step "Save, then redeploy once so the build picks them up"
step "  (Deployments → latest → Retry deployment)."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Point the domain at Pages"
warn "This is the cutover: the live site starts being served by Cloudflare."
say "Only do this once a Pages build has succeeded and its *.pages.dev URL"
say "looks right. Check that first — it is the whole safety net."
confirm "Has a Pages build succeeded and does the pages.dev site look correct?"
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT/domains"
step "Add a custom domain: glasgowtheatre.com"
step "Add a second one: www.glasgowtheatre.com"
step "Cloudflare replaces the GitHub Pages DNS records automatically."
step "Wait for both to show 'Active'."
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Deploy hook — the URL that starts a build"
say "The daily Worker POSTs to this to trigger a rebuild."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT/settings/builds-deployments"
step "Find 'Deploy hooks' → Add deploy hook."
step "Name it 'daily refresh', branch 'main', then create it."
step "Copy the URL it gives you."
ask_secret DEPLOY_HOOK "Paste the deploy hook URL:"
write_env DEPLOY_HOOK "$DEPLOY_HOOK"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Deploy the daily cron Worker"
say "Cloudflare Pages has no scheduled builds, so a tiny Worker runs at"
say "05:17 UTC each day and calls the deploy hook."
TRIGGER_KEY="$(LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32)"
write_env TRIGGER_KEY "$TRIGGER_KEY"
say "Generated a key for manual triggers and saved it to .env."
say ""
step "A browser window will open for wrangler to log in."
confirm "Run the Worker deploy now?"
(
  cd cloudflare || exit 1
  npx --yes wrangler login
  printf '%s' "$DEPLOY_HOOK" | npx --yes wrangler secret put DEPLOY_HOOK
  printf '%s' "$TRIGGER_KEY"  | npx --yes wrangler secret put TRIGGER_KEY
  npx --yes wrangler deploy
) || warn "Worker deploy did not complete — see the error above, then rerun: cd cloudflare && npx wrangler deploy"
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Check it end to end"
say "Trigger one build by hand and watch it work."
say ""
step "Start a build:"
say "    curl -X POST \"\$DEPLOY_HOOK\"   # from .env"
say ""
step "Watch it in the dashboard:"
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$CF_PAGES_PROJECT"
step "The build log should show: refresh → tagging → tests → build → report."
step "The first report run only sets a baseline; the next one that finds new"
step "  shows will email $REPORT_TO."
say ""
step "Once the domain is Active, confirm the live feed exists:"
say "    curl -s https://glasgowtheatre.com/data/events.json | head -c 200"
say ""
step "Confirm the cron is registered:"
say "    cd cloudflare && npx wrangler deployments list"
pause

finish
